// Auto-generated by generate-dashboard-data.sh — DO NOT EDIT MANUALLY
// Generated at: 2026-05-19T02:17:05Z
// Source: Boomi Platform API (live tenant query)

window.DASHBOARD_DATA = {
  "generatedAt": "2026-05-19T02:17:05Z",
  "tenant": "boomi_saurabhsingh-FI5Q23",
  "environment": "Production",
  "envId": "2666f02a-2585-431d-b720-ab5e099f7586",
  "atomName": "Production Training Cloud",
  "windowStart": "2026-04-19T02:17:05Z",
  "windowEnd": "2026-05-19T02:17:05Z",
  "metrics": {
    "deployments": 17,
    "deploymentsActive": 8,
    "deploymentsDormant": 7,
    "executionsTotal": 12034,
    "executionsComplete": 11974,
    "executionsError": 15,
    "executionsDiscarded": 45,
    "successRate": 99.5,
    "avgDurationMs": 8856,
    "dailyAvg": 401,
    "health": {
      "healthy": 5,
      "attention": 2,
      "critical": 1,
      "dormant": 7
    }
  },
  "deployments": [
    {
      "id": "7513531e-8c1e-4f29-bc0f-51b140533248",
      "deploymentId": "dec01c28-a45d-4cb1-9f47-ba1539949721",
      "name": "CEO-Dashboard",
      "folder": "CEO-Dashboard",
      "type": "process",
      "version": 4,
      "deployedAt": "2026-05-19T01:54:10Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 15,
      "status": "healthy"
    },
    {
      "id": "7854af1f-426a-4aff-9432-60b54d2c9aac",
      "deploymentId": "2daa3783-e592-4218-abb9-f39e5de8d2e1",
      "name": "NTTDemo-PublicDashboard-Process",
      "folder": "NTTDemo-PublicDashboard",
      "type": "process",
      "version": 1,
      "deployedAt": "2026-05-18T11:20:29Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 3,
      "status": "healthy"
    },
    {
      "id": "a2bc729b-35c1-47a9-befd-0634a60dccff",
      "deploymentId": "1c26a475-aa34-4550-a49b-3b76a0277cd4",
      "name": "NTTDemo-Order-JSON-to-XML-Process",
      "folder": "NTTDemo-OrderJsonToXml",
      "type": "process",
      "version": 1,
      "deployedAt": "2026-05-18T08:06:51Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 1,
      "status": "healthy"
    },
    {
      "id": "8106e56b-b013-414f-810f-8a0546b49b2f",
      "deploymentId": "2ac942fe-10f3-410f-a5f8-6907588c099a",
      "name": "P_O2C_Twilio_Inbound",
      "folder": "O2C-QAD",
      "type": "process",
      "version": 22,
      "deployedAt": "2026-05-13T17:28:00Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 121,
      "status": "healthy"
    },
    {
      "id": "fe20ef15-b107-4f23-b26b-291f4ab277e1",
      "deploymentId": "eb02685a-1f3a-4da2-9f6f-57cfbed99c94",
      "name": "P_O2C_WhatsApp_to_QAD_Main",
      "folder": "O2C-QAD",
      "type": "process",
      "version": 3,
      "deployedAt": "2026-05-13T11:18:07Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 12,
      "status": "critical"
    },
    {
      "id": "319b49d7-e291-471a-9c8a-370530166be5",
      "deploymentId": "61f993ce-08af-4bd5-a483-7501c65d8310",
      "name": "Twilio Inbound API for QAD SO",
      "folder": "O2C-QAD",
      "type": "webservice",
      "version": 1,
      "deployedAt": "2026-05-13T09:06:41Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 0,
      "status": "info"
    },
    {
      "id": "3f79652d-f723-417a-a4f3-b44736ab19a5",
      "deploymentId": "cfae4d77-5b32-44b0-80f9-8718b6798060",
      "name": "test",
      "folder": "Boomi_SaurabhSingh",
      "type": "process",
      "version": 2,
      "deployedAt": "2026-05-13T08:23:24Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 0,
      "status": "dormant"
    },
    {
      "id": "49a8630e-652b-4fea-899c-bae4d99b77f5",
      "deploymentId": "9c24ff6b-e123-4807-ab53-e3cd00f3b737",
      "name": "ElectroMart_OrderUpdate_API",
      "folder": "ElectroMart-OrderToCash",
      "type": "process",
      "version": 3,
      "deployedAt": "2026-05-07T08:26:55Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 5,
      "status": "healthy"
    },
    {
      "id": "99a71e43-f00e-4403-80af-918e110e1cba",
      "deploymentId": "54c32642-5d04-47a5-a04d-9738315dbf58",
      "name": "ElectroMart_OrderLookup_API",
      "folder": "ElectroMart-OrderToCash",
      "type": "process",
      "version": 3,
      "deployedAt": "2026-05-07T08:08:52Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 27,
      "status": "attention"
    },
    {
      "id": "14ec7217-cab7-4ce1-a68b-81b202962c3b",
      "deploymentId": "9484dabd-501a-471a-ad07-567473036f35",
      "name": "acceptEditstest",
      "folder": "LuckFrozen-Demo",
      "type": "process",
      "version": 1,
      "deployedAt": "2026-05-05T15:42:32Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 0,
      "status": "dormant"
    },
    {
      "id": "bebdde37-f927-47cc-97b8-6c6e8127c3c5",
      "deploymentId": "a92651c4-bbf4-47a1-82f5-80ddb98c84ff",
      "name": "bash-hello",
      "folder": "LuckFrozen-Demo",
      "type": "process",
      "version": 4,
      "deployedAt": "2026-05-05T15:38:05Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 0,
      "status": "dormant"
    },
    {
      "id": "2191dd75-f5e3-4c9f-a7e4-203ed8058887",
      "deploymentId": "cf07f880-251d-44fe-ad95-1b4c7dbefa44",
      "name": "LuckFrozen-Demo - Live NYC Weather via HTTP",
      "folder": "LuckFrozen-Demo",
      "type": "process",
      "version": 1,
      "deployedAt": "2026-05-05T07:43:35Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 0,
      "status": "dormant"
    },
    {
      "id": "a0831293-fbd9-442b-9fe0-7443a6636152",
      "deploymentId": "d085bdd3-0404-493a-b03c-147402271f50",
      "name": "Product Web Service",
      "folder": "Boomi_SaurabhSingh",
      "type": "process",
      "version": 1,
      "deployedAt": "2026-03-17T11:47:54Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 0,
      "status": "dormant"
    },
    {
      "id": "1e854d95-61ce-40d4-bfd3-f5ce7dcc91d7",
      "deploymentId": "9289282f-8e30-46cc-b39b-328ead4856c9",
      "name": "[Event Streams] Handle Slack App Messages - RKOM",
      "folder": "Bundle-RKOM - Building Agentic Workflows Tech Session Bundle-2026-02-23-09:28",
      "type": "process",
      "version": 1,
      "deployedAt": "2026-02-23T15:59:46Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 0,
      "status": "dormant"
    },
    {
      "id": "d217f418-8369-4248-afb8-da3f29ef723b",
      "deploymentId": "699d6f5f-89e6-4469-ae74-b494504ebb16",
      "name": "SN Incident Create Proxy",
      "folder": "Boomi_SaurabhSingh",
      "type": "webservice.external",
      "version": 1,
      "deployedAt": "2025-11-26T07:09:33Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 0,
      "status": "info"
    },
    {
      "id": "37214c83-2dfc-4c4c-8203-a0f40327e699",
      "deploymentId": "b2c7ffe1-2bae-4176-8848-c9af176a6208",
      "name": "Ticket v5 Gmail",
      "folder": "Created_by_BoomiAI",
      "type": "process",
      "version": 4,
      "deployedAt": "2025-11-10T08:35:27Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 11850,
      "status": "attention"
    },
    {
      "id": "874463b2-6ba5-48a6-a055-ccab7fb0ff43",
      "deploymentId": "132da947-43ee-4c07-9883-58082f0eaadb",
      "name": "Ticket v4",
      "folder": "Created_by_BoomiAI",
      "type": "process",
      "version": 10,
      "deployedAt": "2025-11-06T08:35:38Z",
      "deployedBy": "saurabh.singh@boomi.com",
      "runs": 0,
      "status": "dormant"
    }
  ],
  "processStats": {
    "37214c83-2dfc-4c4c-8203-a0f40327e699": {
      "processId": "37214c83-2dfc-4c4c-8203-a0f40327e699",
      "name": "Ticket v5 Gmail",
      "type": "exec_sched",
      "total": 11850,
      "complete": 11804,
      "error": 1,
      "discarded": 45,
      "avgMs": 8831,
      "maxMs": 482136,
      "inDocs": 1,
      "outDocs": 2,
      "first": "2026-04-19T08:00:01Z",
      "last": "2026-05-07T11:51:00Z",
      "note": "🟡 Concurrency issue — schedule racing itself. Increase poll interval or enable allowSimultaneous."
    },
    "49a8630e-652b-4fea-899c-bae4d99b77f5": {
      "processId": "49a8630e-652b-4fea-899c-bae4d99b77f5",
      "name": "ElectroMart_OrderUpdate_API",
      "type": "exec_listener",
      "total": 5,
      "complete": 5,
      "error": 0,
      "discarded": 0,
      "avgMs": 3347,
      "maxMs": 3778,
      "inDocs": 5,
      "outDocs": 0,
      "first": "2026-05-07T11:39:48Z",
      "last": "2026-05-07T12:58:38Z",
      "note": "🟢 Healthy when invoked (low-volume — verify caller integration if expecting more traffic)."
    },
    "7513531e-8c1e-4f29-bc0f-51b140533248": {
      "processId": "7513531e-8c1e-4f29-bc0f-51b140533248",
      "name": "CEO-Dashboard",
      "type": "exec_listener",
      "total": 15,
      "complete": 15,
      "error": 0,
      "discarded": 0,
      "avgMs": 5490,
      "maxMs": 21692,
      "inDocs": 15,
      "outDocs": 0,
      "first": "2026-05-18T12:42:56Z",
      "last": "2026-05-18T13:17:04Z",
      "note": "🟢 Healthy — running cleanly."
    },
    "7854af1f-426a-4aff-9432-60b54d2c9aac": {
      "processId": "7854af1f-426a-4aff-9432-60b54d2c9aac",
      "name": "NTTDemo-PublicDashboard-Process",
      "type": "exec_listener",
      "total": 3,
      "complete": 3,
      "error": 0,
      "discarded": 0,
      "avgMs": 8298,
      "maxMs": 16235,
      "inDocs": 3,
      "outDocs": 0,
      "first": "2026-05-18T11:25:05Z",
      "last": "2026-05-18T12:43:01Z",
      "note": "🟢 Healthy when invoked (low-volume — verify caller integration if expecting more traffic)."
    },
    "8106e56b-b013-414f-810f-8a0546b49b2f": {
      "processId": "8106e56b-b013-414f-810f-8a0546b49b2f",
      "name": "P_O2C_Twilio_Inbound",
      "type": "exec_listener",
      "total": 121,
      "complete": 121,
      "error": 0,
      "discarded": 0,
      "avgMs": 10495,
      "maxMs": 140116,
      "inDocs": 121,
      "outDocs": 43,
      "first": "2026-05-13T09:14:32Z",
      "last": "2026-05-18T08:14:28Z",
      "note": "🟢 Healthy — running cleanly."
    },
    "99a71e43-f00e-4403-80af-918e110e1cba": {
      "processId": "99a71e43-f00e-4403-80af-918e110e1cba",
      "name": "ElectroMart_OrderLookup_API",
      "type": "exec_listener",
      "total": 27,
      "complete": 25,
      "error": 2,
      "discarded": 0,
      "avgMs": 5053,
      "maxMs": 26186,
      "inDocs": 27,
      "outDocs": 0,
      "first": "2026-05-07T11:29:08Z",
      "last": "2026-05-13T09:14:00Z",
      "note": "🟡 Some errors — review individual error messages."
    },
    "a2bc729b-35c1-47a9-befd-0634a60dccff": {
      "processId": "a2bc729b-35c1-47a9-befd-0634a60dccff",
      "name": "NTTDemo-Order-JSON-to-XML-Process",
      "type": "exec_manual",
      "total": 1,
      "complete": 1,
      "error": 0,
      "discarded": 0,
      "avgMs": 3306,
      "maxMs": 3306,
      "inDocs": 1,
      "outDocs": 0,
      "first": "2026-05-18T08:07:14Z",
      "last": "2026-05-18T08:07:14Z",
      "note": "🟢 Healthy when invoked (low-volume — verify caller integration if expecting more traffic)."
    },
    "fe20ef15-b107-4f23-b26b-291f4ab277e1": {
      "processId": "fe20ef15-b107-4f23-b26b-291f4ab277e1",
      "name": "P_O2C_WhatsApp_to_QAD_Main",
      "type": "sub_process",
      "total": 12,
      "complete": 0,
      "error": 12,
      "discarded": 0,
      "avgMs": 32987,
      "maxMs": 135640,
      "inDocs": 0,
      "outDocs": 0,
      "first": "2026-05-13T09:14:36Z",
      "last": "2026-05-13T09:37:57Z",
      "note": "🔴 BROKEN — all runs failed. Review error message and redeploy."
    }
  },
  "errors": [
    {
      "at": "2026-05-13T09:37:57Z",
      "process": "P_O2C_WhatsApp_to_QAD_Main",
      "type": "sub_process",
      "msg": "Severe errors occurred during start shape execution, terminating process.; Caused by: Missing or unexpected listen action start data com.boomi.process.util.StandaloneStartData@3fdef60; Caused by: Cannot load read store from unknown info com.boomi.process.util.StandaloneStartData@3fdef60"
    },
    {
      "at": "2026-05-13T09:35:31Z",
      "process": "P_O2C_WhatsApp_to_QAD_Main",
      "type": "sub_process",
      "msg": "Severe errors occurred during start shape execution, terminating process.; Caused by: Missing or unexpected listen action start data com.boomi.process.util.StandaloneStartData@75c29991; Caused by: Cannot load read store from unknown info com.boomi.process.util.StandaloneStartData@75c29991"
    },
    {
      "at": "2026-05-13T09:33:06Z",
      "process": "P_O2C_WhatsApp_to_QAD_Main",
      "type": "sub_process",
      "msg": "Severe errors occurred during start shape execution, terminating process.; Caused by: Missing or unexpected listen action start data com.boomi.process.util.StandaloneStartData@3eb35ad7; Caused by: Cannot load read store from unknown info com.boomi.process.util.StandaloneStartData@3eb35ad7"
    },
    {
      "at": "2026-05-13T09:30:58Z",
      "process": "P_O2C_WhatsApp_to_QAD_Main",
      "type": "sub_process",
      "msg": "Unexpected error occurred while initializing a shape.; Caused by: Unable to load settings from XML.; Caused by: unexpected element (uri:\"\", local:\"GenericConnectionConfig\"). Expected elements are <{}WebServicesServerListenAction>"
    },
    {
      "at": "2026-05-13T09:29:00Z",
      "process": "P_O2C_WhatsApp_to_QAD_Main",
      "type": "sub_process",
      "msg": "Unexpected error occurred while initializing a shape.; Caused by: Unable to load settings from XML.; Caused by: unexpected element (uri:\"\", local:\"GenericConnectionConfig\"). Expected elements are <{}WebServicesServerListenAction>"
    },
    {
      "at": "2026-05-13T09:28:46Z",
      "process": "P_O2C_WhatsApp_to_QAD_Main",
      "type": "sub_process",
      "msg": "Unexpected error occurred while initializing a shape.; Caused by: Unable to load settings from XML.; Caused by: unexpected element (uri:\"\", local:\"GenericConnectionConfig\"). Expected elements are <{}WebServicesServerListenAction>"
    },
    {
      "at": "2026-05-13T09:28:33Z",
      "process": "P_O2C_WhatsApp_to_QAD_Main",
      "type": "sub_process",
      "msg": "Unexpected error occurred while initializing a shape.; Caused by: Unable to load settings from XML.; Caused by: unexpected element (uri:\"\", local:\"GenericConnectionConfig\"). Expected elements are <{}WebServicesServerListenAction>"
    },
    {
      "at": "2026-05-13T09:28:20Z",
      "process": "P_O2C_WhatsApp_to_QAD_Main",
      "type": "sub_process",
      "msg": "Unexpected error occurred while initializing a shape.; Caused by: Unable to load settings from XML.; Caused by: unexpected element (uri:\"\", local:\"GenericConnectionConfig\"). Expected elements are <{}WebServicesServerListenAction>"
    },
    {
      "at": "2026-05-13T09:28:07Z",
      "process": "P_O2C_WhatsApp_to_QAD_Main",
      "type": "sub_process",
      "msg": "Unexpected error occurred while initializing a shape.; Caused by: Unable to load settings from XML.; Caused by: unexpected element (uri:\"\", local:\"GenericConnectionConfig\"). Expected elements are <{}WebServicesServerListenAction>"
    },
    {
      "at": "2026-05-13T09:27:52Z",
      "process": "P_O2C_WhatsApp_to_QAD_Main",
      "type": "sub_process",
      "msg": "Unexpected error occurred while initializing a shape.; Caused by: Unable to load settings from XML.; Caused by: unexpected element (uri:\"\", local:\"GenericConnectionConfig\"). Expected elements are <{}WebServicesServerListenAction>"
    },
    {
      "at": "2026-05-13T09:14:41Z",
      "process": "P_O2C_WhatsApp_to_QAD_Main",
      "type": "sub_process",
      "msg": "Unexpected error occurred while initializing a shape.; Caused by: Unable to load settings from XML.; Caused by: unexpected element (uri:\"\", local:\"GenericConnectionConfig\"). Expected elements are <{}WebServicesServerListenAction>"
    },
    {
      "at": "2026-05-13T09:14:36Z",
      "process": "P_O2C_WhatsApp_to_QAD_Main",
      "type": "sub_process",
      "msg": "Unexpected error occurred while initializing a shape.; Caused by: Unable to load settings from XML.; Caused by: unexpected element (uri:\"\", local:\"GenericConnectionConfig\"). Expected elements are <{}WebServicesServerListenAction>"
    },
    {
      "at": "2026-05-07T11:30:11Z",
      "process": "ElectroMart_OrderLookup_API",
      "type": "exec_listener",
      "msg": "[Input ProfileLocation: Root; DocumentLocation: /Root]: Unable to create JSON files from data, the document may not be well-formed json"
    },
    {
      "at": "2026-05-07T11:29:08Z",
      "process": "ElectroMart_OrderLookup_API",
      "type": "exec_listener",
      "msg": "[Input ProfileLocation: Root; DocumentLocation: /Root]: Unable to create JSON files from data, the document may not be well-formed json"
    },
    {
      "at": "2026-04-30T08:14:00Z",
      "process": "Ticket v5 Gmail",
      "type": "exec_sched",
      "msg": "Fatal error in Start Shape; Caused by: * BYE JavaMail Exception: java.net.SocketTimeoutException: Read timed out"
    }
  ],
  "discards": {
    "total": 45,
    "process": "Ticket v5 Gmail",
    "cause": "Process is already running (concurrency overlap)",
    "pattern": "Scheduled poll fires while previous execution is still running. Concurrent invocations are blocked by allowSimultaneous=false.",
    "dates": [
      "2026-04-21",
      "2026-04-30",
      "2026-05-04",
      "2026-05-05"
    ]
  },
  "environments": [
    {
      "name": "Production",
      "id": "2666f02a-2585-431d-b720-ab5e099f7586",
      "classification": "PROD",
      "isDefault": true
    },
    {
      "name": "Test",
      "id": "ee03f301-4b29-45f8-bd4b-b93154b35546",
      "classification": "TEST",
      "isDefault": false
    },
    {
      "name": "Local Env",
      "id": "61932bac-4fc6-407c-8021-8f908c5fdd75",
      "classification": "PROD",
      "isDefault": false
    },
    {
      "name": "Agent Web Services",
      "id": "ac1a8bf5-dd05-4009-928d-79567a17e11c",
      "classification": "PROD",
      "isDefault": false
    }
  ],
  "recommendations": [
    {
      "priority": "P0",
      "title": "Fix P_O2C_WhatsApp_to_QAD_Main",
      "why": "100% failure rate — affected runs not being processed",
      "how": "Investigate error message in process detail, fix configuration, redeploy",
      "processId": "fe20ef15-b107-4f23-b26b-291f4ab277e1"
    },
    {
      "priority": "P1",
      "title": "Tune Ticket v5 Gmail concurrency",
      "why": "45 concurrency discards in last 30 days",
      "how": "Increase poll interval or enable allowSimultaneous in process configuration",
      "processId": "37214c83-2dfc-4c4c-8203-a0f40327e699"
    },
    {
      "priority": "P1",
      "title": "Add input validation to Ticket v5 Gmail",
      "why": "1 errors — may be caller-side input issues",
      "how": "Wrap in Try/Catch with explicit error response so callers learn faster",
      "processId": "37214c83-2dfc-4c4c-8203-a0f40327e699"
    },
    {
      "priority": "P1",
      "title": "Add input validation to ElectroMart_OrderLookup_API",
      "why": "2 errors — may be caller-side input issues",
      "how": "Wrap in Try/Catch with explicit error response so callers learn faster",
      "processId": "99a71e43-f00e-4403-80af-918e110e1cba"
    },
    {
      "priority": "P2",
      "title": "Undeploy long-idle processes",
      "why": "Reduce tenant clutter: 7 dormant deployments",
      "how": "Use boomi-undeploy.sh on processes with > 60 days idle"
    },
    {
      "priority": "P2",
      "title": "Add Process Reporting alerts",
      "why": "Proactive notification when error rates spike",
      "how": "Platform → Notifications → ERROR threshold per environment"
    }
  ]
}
;
